  swagger: '2.0'
  info:
    description: Api Documentation
    version: '1.0'
    title: Api Documentation
    contact: {}
    license:
      name: Apache 2.0
      url: 'http://www.apache.org/licenses/LICENSE-2.0'
  host: 'localhost:8080'
  basePath: /
  tags:
    - name: heroes
      description: Heroes
  paths:
    /heroes:
      get:
        tags:
          - heroes
        summary: Returns all the heroes
        operationId: getAll
        produces:
          - '*/*'
        responses:
          '200':
            description: OK
            schema:
              $ref: '#/definitions/HeroeDTO'
          '401':
            description: Unauthorized
          '403':
            description: Forbidden
          '404':
            description: Not Found
      put:
        tags:
          - heroes
        summary: Inserts or updates a heroe
        operationId: upsert
        consumes:
          - application/json
        produces:
          - '*/*'
        parameters:
          - in: body
            name: heroesDto
            description: heroesDto
            required: true
            schema:
              $ref: '#/definitions/HeroeDTO'
        responses:
          '200':
            description: OK
          '201':
            description: Created
          '401':
            description: Unauthorized
          '403':
            description: Forbidden
          '404':
            description: Not Found
    '/heroes/{id}':
      delete:
        tags:
          - heroes
        summary: Deletes a heroe by ID
        operationId: delete
        produces:
          - '*/*'
        parameters:
          - name: id
            in: path
            description: id
            required: true
            type: integer
            format: int32
        responses:
          '200':
            description: OK
          '204':
            description: No Content
          '401':
            description: Unauthorized
          '403':
            description: Forbidden
  definitions:
    HeroeDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
      title: HeroeDTO
  

