server:
 port: 8080
 servlet:
  contextPath: /heroes

spring:
 profiles:
  active: test
 datasource:
  driverClassName: org.h2.Driver
  url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  username: user
  password: password
 jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  show-sql: true
  properties:
   hibernate:
    format_sql: true

 h2:
  console:
   enabled: true
   settings:
    web-allow-others: true
